-- CreateTable
CREATE TABLE "DamageReport" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ownerName" TEXT NOT NULL,
    "ownerAddress" TEXT,
    "driverName" TEXT,
    "driverAddress" TEXT,
    "customerEmail" TEXT NOT NULL,
    "customerPhone" TEXT,
    "vehiclePlate" TEXT NOT NULL,
    "vehicleMake" TEXT NOT NULL,
    "vehicleModel" TEXT NOT NULL,
    "vehicleYear" INTEGER,
    "vehicleVin" TEXT,
    "hasCasco" BOOLEAN NOT NULL DEFAULT false,
    "cascoInsurer" TEXT,
    "liabilityInsurer" TEXT,
    "accidentDate" TIMESTAMP(3),
    "accidentCountry" TEXT,
    "accidentCity" TEXT,
    "accidentStreet" TEXT,
    "policeInvolved" BOOLEAN NOT NULL DEFAULT false,
    "policeReportNo" TEXT,
    "otherVehiclePlate" TEXT,
    "otherVehicleType" TEXT,
    "otherVehicleColor" TEXT,
    "additionalParties" TEXT,
    "damageDescription" TEXT,
    "damagePoints" JSONB,
    "photoUrls" TEXT[],
    "liableParty" TEXT,
    "underInfluence" BOOLEAN NOT NULL DEFAULT false,
    "licenseValid" BOOLEAN NOT NULL DEFAULT true,
    "taxNumber" TEXT,
    "consentToPhotocopy" BOOLEAN NOT NULL DEFAULT false,
    "ownerSignatureUrl" TEXT,
    "driverSignatureUrl" TEXT,
    "gdprConsent" BOOLEAN NOT NULL DEFAULT false,
    "emailSentAt" TIMESTAMP(3),

    CONSTRAINT "DamageReport_pkey" PRIMARY KEY ("id")
);
